<?php

declare(strict_types=1);

/*
 * SwaggerPetstoreLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SwaggerPetstoreLib;

/**
 * Interface for defining the behavior of Authentication.
 */
interface CustomAuthenticationCredentials
{
    /**
     * String value for password.
     */
    public function getPassword(): string;

    /**
     * Checks if provided credentials match with existing ones.
     *
     * @param string $password
     */
    public function equals(string $password): bool;
}
