<?php

declare(strict_types=1);

/*
 * SwaggerPetstoreLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SwaggerPetstoreLib;

/**
 * Baseurl aliases
 */
class Server
{
    public const SERVER1 = 'server1';

    public const SERVER2 = 'server2';

    public const AUTH_SERVER = 'auth server';
}
